### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hampoelz** [alex-shpak/keemob#5]
Hello, how can I install this app? - Find nowhere a instruction ...

**Comment by alex-shpak** [comment]
Hi!
I uploaded apk file. Note that it's not ready for real use yet! But works so far on my device.

https://github.com/alex-shpak/keemob/releases/tag/0.0.1

**Comment by hampoelz** [comment]
Hey, thanks for the quick reply and the apk file. Would it still be possible to add a German translation?

**Comment by alex-shpak** [comment]
I have uploaded fresh build, it now contains german translation by default. Also various issues were fixed.
Please delete old version of application since new build is signed with proper keys.

https://github.com/alex-shpak/keemob/releases/tag/0.0.2
