### ISSUE TITLE
Keystore password

### ISSUE THREAD

**Issue by JulesLassara** [alex-shpak/keemob#7]
Hello,

I'm trying to compile your application but for the last step, I have to enter a "Keestore password for signer #1:"

I'm blocked. Can you help me ?

Jules Lassara

**Comment by alex-shpak** [comment]
Hi!
If you are still interested,
you can use your local keystore to sign an app, see [here](https://stackoverflow.com/a/39330177)

Also there is build available [here](https://github.com/alex-shpak/keemob/releases/tag/0.0.2) signed by my key
